package com.dbp.model;

import java.util.Date;

public class SysUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.uid
     *
     * @mbggenerated
     */
    private String uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.username
     *
     * @mbggenerated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.benabled
     *
     * @mbggenerated
     */
    private Integer benabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.sphone
     *
     * @mbggenerated
     */
    private String sphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_user.dcreatedate
     *
     * @mbggenerated
     */
    private Date dcreatedate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.uid
     *
     * @return the value of sys_user.uid
     *
     * @mbggenerated
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.uid
     *
     * @param uid the value for sys_user.uid
     *
     * @mbggenerated
     */
    public void setUid(String uid) {
        this.uid = uid == null ? null : uid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.username
     *
     * @return the value of sys_user.username
     *
     * @mbggenerated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.username
     *
     * @param username the value for sys_user.username
     *
     * @mbggenerated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.password
     *
     * @return the value of sys_user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.password
     *
     * @param password the value for sys_user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.benabled
     *
     * @return the value of sys_user.benabled
     *
     * @mbggenerated
     */
    public Integer getBenabled() {
        return benabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.benabled
     *
     * @param benabled the value for sys_user.benabled
     *
     * @mbggenerated
     */
    public void setBenabled(Integer benabled) {
        this.benabled = benabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.sphone
     *
     * @return the value of sys_user.sphone
     *
     * @mbggenerated
     */
    public String getSphone() {
        return sphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.sphone
     *
     * @param sphone the value for sys_user.sphone
     *
     * @mbggenerated
     */
    public void setSphone(String sphone) {
        this.sphone = sphone == null ? null : sphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_user.dcreatedate
     *
     * @return the value of sys_user.dcreatedate
     *
     * @mbggenerated
     */
    public Date getDcreatedate() {
        return dcreatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_user.dcreatedate
     *
     * @param dcreatedate the value for sys_user.dcreatedate
     *
     * @mbggenerated
     */
    public void setDcreatedate(Date dcreatedate) {
        this.dcreatedate = dcreatedate;
    }
}